# Generated by Django 6.0.6 on 2026-06-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readmetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='readmetemplate',
            name='fork_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readmetemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated unique identifier for shareable preview URLs.', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='readmetemplate',
            name='template_id',
            field=models.CharField(choices=[('modern', 'Modern Badges'), ('minimalist', 'Minimalist'), ('creative', 'Creative Banner')], default='modern', max_length=32),
        ),
        migrations.AddField(
            model_name='readmetemplate',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readmetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
